### PR TITLE
Compensate for local url bug in wkhtmltopdf

### PR DESCRIPTION
**Pull request by griff**
Because of the bug wkhtmltopdf/wkhtmltopdf#2051 when the html contains
relative links with query parameters wkhtmltopdf will exit with an
error code but still generate the pdf correctly. This commit handles
that case and adds tests to illustrate the problem.

### CODE REVIEW

**Comment by andrewferrier** [comment]
I've taken a look at the test cases, and I think I see what you're trying to do. In general I wanted to make sure that email2pdf *did* fail by default in this case, because it's being fed an email which is by definition invalid (it refers to invalid URLs). What do you think about adding a --forgive-missing-links flag to enable this change in behaviour you are suggesting?

**Comment by andrewferrier** [comment]
This was the principle I'd documented:

'Try to keep email2pdf as "safe" as possible by default. Without supplying any potentially harmful command-line options, email2pdf will not ignore parts of the email it shouldn't, and will fail in the standard UNIX way with an error code if it has any significant doubts about the integrity of the email it's reading, or any other serious error occurs.'

**Comment by griff** [comment]
Well if you want it to fail on local links you might want to do something else than what I have done here. 

This commit only compensates for the fact that wkhtmltopdf does two completely different things depending on whether the local URL has a query parameter or not. With the current options you are running wkhtmltopdf with it will silently ignore script urls like /test.js and email2pdf will succeed while wkhtmltopdf will fail and return an exit code of 1 when the url is /test.js?muh which is very inconsistent. 

My change only makes the behavior of these two urls consistent by also silently ignoring urls with query parameters.

**Comment by andrewferrier** [comment]
OK. To be clear, I don't want to make it fail on local links. I didn't read your original comment carefully enough - I think I understand now. However, my concern is that this change might make email2pdf too forgiving of other URLs which are invalid (for example, a standard remote URL which returns a 404). I'd like to add a few more test cases of my own just to make sure the change is safe. I'll take a look at that a bit later.

By the way, you are my first pull requester - very pleased! Thanks for your contribution.

**Comment by andrewferrier** [comment]
Have tested this a bit more, seems OK, my primary concern at the moment is the commenting-out of the returncode check. I see what you're trying to do (it exits with rc>0 in that case), just trying to think of a "safer" way not to accidentally ignore other wkhtmltopdf errors...

**Comment by andrewferrier** [comment]
OK, I've made some additional changes to try and make this more robust. You can see them here:

https://github.com/andrewferrier/email2pdf/compare/master...andrewferrier:griff-bugfix/content-not-found-error

Essentially, my objective was to make sure that if there is *unexpected* stderr from wkhtmltopdf, *or* a non-zero error code with empty stderr, that email2pdf bombs out. I didn't want to just ignore the rc from wkhtmltopdf.

I think that still meets your criteria, what do you think?

**Comment by griff** [comment]
That looks good.

**Comment by andrewferrier** [comment]
Thanks. Applied.

**Pull request merged**
